# Docker environment configuration
spring:
  kafka:
    consumer:
      bootstrap-servers: Kafka00Service:9092,Kafka01Service:9092,Kafka02Service:9092

otel:
  exporter:
    otlp:
      endpoint: http://collector:4317
