service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [nop]
      processors: [batch]
      exporters: [nop]
  telemetry:
    resource:
      service.name: jaeger-query
    logs:
      level: info

extensions:
  healthcheckv2:
    use_v2: true
    http:
      endpoint: 0.0.0.0:16687

  jaeger_storage:
    backends:
      query_storage:
        elasticsearch:
          server_urls:
            - http://elasticsearch:9200
          indices:
            index_prefix: "jaeger-prod"
          use_aliases: true
          use_ilm: true
          create_mappings: false # 2.7 부터 넣어야 함
          # https://docs.google.com/document/d/1rabu8zvjoZeHx-HNqvK5kjsujMEBC7DkR2MYeOvB6HI/edit?tab=t.0#heading=h.abjgb642qlsg
          # https://www.jaegertracing.io/docs/1.73/deployment/cli/ (여기서 --es.create-index-templates 이거 검색해서 내용보기) -> 1.7.3 버전
          # Original settings that were working in 2.6.0
          # elastic search tls 연결 시 사용
#          auth:
#            basic:
#              username: ${elasticsearch.username}
#              password: ${elasticsearch.password}
#          tls:
#            ca_file: certs/ca.crt
#            insecure_skip_verify: true # ca file 의 SAN 검증 무시
  jaeger_query:
    storage:
      traces: query_storage
    base_path: /
    ui:
      config_file: etc/jaeger/ui-config.json
      log_access: true
    grpc:
      endpoint: 0.0.0.0:16685
    http:
      endpoint: 0.0.0.0:16686

receivers:
  nop:

processors:
  batch:

exporters:
  nop:
